# Generated by Django 5.1 on 2024-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0003_delete_timedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_minutes', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('time_recorded', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
