# Generated by Django 5.1 on 2024-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_timerecord_delete_timedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='time_in_minutes',
            field=models.FloatField(),
        ),
    ]
